apiVersion: apps/v1
kind: Deployment
metadata:
  name: coviddashboard
  labels:
    app: coviddashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coviddashboard
  template:
    metadata:
      labels:
        app: coviddashboard
    spec:
      containers:
        - name: coviddashboard
          image: username/coviddashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5